# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
  db_driver: orm

  metadata:
    type: attribute
  mappings:
    user:
      uri_prefix: /images/user
      upload_destination: "%kernel.project_dir%/public/images/user"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    categorie:
      uri_prefix: /images/categorie
      upload_destination: "%kernel.project_dir%/public/images/categorie"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    protype:
      uri_prefix: /images/protype
      upload_destination: "%kernel.project_dir%/public/images/protype"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
