controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

programmes_index:
    path: /programmes/{type}
    controller: 'App\Controller\Frontend\ProgrammeController::index'